In [2]:
import requests

In [5]:
response = requests.get('http://127.0.0.1:8000')
response.text

'{"message":"Hello World"}'

In [11]:
response = requests.get('http://127.0.0.1:8000/hello?name=Kevin')
response.text

'{"message":"Hello Kevin"}'

In [13]:
data = {'name': 5}

response = requests.get('http://127.0.0.1:8000/hello', params=data)
response.text

'{"message":"Hello 5"}'

In [16]:
response = requests.get('http://127.0.0.1:8000/hello/5')
response.text

'{"message":"Hello 5"}'

In [59]:
from pydantic import BaseModel


class Credit(BaseModel):
    age: int
    job: int
    marital: int
    education: int
    default: int
    balance: int
    housing: int
    loan: int
    campaign: int
    pdays: int
    previous: int
    poutcome: int


data = {
    'age': 58,
    'job': 1,
    'marital': 1,
    'education': 2,
    'default': 0,
    'balance': 2143,
    'housing': 1,
    'loan': 0,
    'campaign': 1,
    'pdays': -1,
    'previous': 0,
    'poutcome': 3
}


credit = Credit(**data)

In [63]:
list(credit.dict().values())

/var/folders/xg/zbz96gcd1l318nfzl96_m9dm0000gn/T/ipykernel_37835/1180350603.py:1: PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
  list(credit.dict().values())


[58, 1, 1, 2, 0, 2143, 1, 0, 1, -1, 0, 3]

In [76]:
import pickle

with open('model.pkl', 'rb') as f: model = pickle.load(f)
predict_value = int(model.predict([list(credit.dict().values())])[0])
predict_value

/Users/kevinduranty/Desktop/my_fastapi/venv_fastapi/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


0

In [74]:
int(model.predict([list(credit.dict().values())])[0])

/var/folders/xg/zbz96gcd1l318nfzl96_m9dm0000gn/T/ipykernel_37835/2385446455.py:1: PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
  int(model.predict([list(credit.dict().values())])[0])
/Users/kevinduranty/Desktop/my_fastapi/venv_fastapi/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


0

In [34]:


list(data.dict().values())

/var/folders/xg/zbz96gcd1l318nfzl96_m9dm0000gn/T/ipykernel_37835/2584215970.py:1: PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
  list(data.dict().values())


[58, 1, 1, 2, 0, 2143, 1, 0, 1, -1, 0, 3]

In [87]:
# Test du point de terminaison predict avec une requête POST
data = {'age': 58,
    'job': 1,
    'marital': 1,
    'education': 2,
    'default': 0,
    'balance': 2143,
    'housing': 1,
    'loan': 0,
    'campaign': 1,
    'pdays': -1,
    'previous': 0,
    'poutcome': 3
}
response = requests.post('http://127.0.0.1:8000/predict', json=data)
response.text

'{"pred":0}'

In [92]:
eval('print("hello")')

hello


In [26]:
data = {'number': 25}

response = requests.post('http://127.0.0.1:8000/root_square', params=data)
response.content

b'{"result":5.0}'

In [133]:
# READ CSV WITH OPEN
with open('data.csv', 'r') as f: 
    data = f.readlines()

In [137]:
data = data[1:]

In [150]:
X =  [[int(value.replace(' ', '')) for value in line.split(',')[:12]] for line in data]

In [152]:
model.predict(X)

/Users/kevinduranty/Desktop/my_fastapi/venv_fastapi/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0, 0, 0, 0, 0, 0, 0])

In [141]:
len(data[4])

94

In [114]:
[[int(value.replace(' ', '').replace('\n', '')) for value in line.split(',')] for line in data[1:]]

[[0, 2, 1, 3, 0, 0, 1787, 0, 0, 0, 0, 0, 0, 0, 1, 19, 79, 1, 0, 0, 0, 0, 0, 0],
 [1,
  2,
  1,
  0,
  0,
  0,
  4789,
  1,
  0,
  1,
  1,
  0,
  0,
  1,
  1,
  11,
  220,
  1,
  0,
  0,
  1,
  0,
  0,
  0],
 [2,
  1,
  1,
  1,
  0,
  0,
  1350,
  1,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  16,
  185,
  1,
  0,
  0,
  1,
  0,
  0,
  0],
 [3, 1, 1, 2, 0, 0, 1476, 1, 0, 1, 1, 0, 0, 1, 1, 3, 199, 4, 0, 0, 1, 0, 0, 0],
 [4, 2, 1, 2, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 5, 226, 1, 0, 0, 1, 0, 0, 0],
 [5, 2, 1, 3, 0, 0, 747, 0, 0, 0, 0, 0, 0, 0, 1, 23, 141, 2, 0, 0, 0, 0, 0, 0],
 [6, 1, 1, 0, 0, 0, 307, 1, 0, 0, 1, 0, 1, 1, 1, 14, 341, 1, 0, 0, 1, 0, 0, 0]]

In [116]:
model.predict([[int(value.replace(' ', '').replace('\n', '')) for value in line.split(',')[:12]] for line in data[1:]])

/Users/kevinduranty/Desktop/my_fastapi/venv_fastapi/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0, 0, 0, 0, 0, 0, 0])

In [156]:
import pandas as pd
pd.__version__

'2.0.3'

In [159]:
{
        "name": "Hello 1",
        "description": "Hello World"
    }

{'name': 'Hello 1', 'description': 'Hello World'}

In [155]:
# Test endpoint /uploadfile
filpath = 'data.csv'
response = requests.post('http://127.0.0.1:8000/uploadfile', files={'file': open(filpath, 'rb')})
response.text

'{"filename":"[0 0 0 0 0 0 0]"}'

In [3]:
import os
list_files = os.listdir()
list_files

['requirements.txt',
 'venv_fastapi',
 '__pycache__',
 'model.pkl',
 'test.py',
 'data.csv',
 'api.py',
 'test.ipynb']

In [ ]:
\
    --host 0.0.0.0 --default-artifact-root $ARTIFACT_STORE_URI \
    --backend-store-uri $BACKEND_STORE_URI

In [6]:
import mlflow

mlflow.set_tracking_uri("https://isen-mlflow-amine-e1c4c6daefa8.herokuapp.com/")
logged_model = 'runs:/6f5d7ef26b6c486ba19f859d6720a6cd/model Bank 22'


# Load model as a PyFuncModel.
loaded_model = mlflow.pyfunc.load_model(logged_model)

2024/02/02 10:31:45 WARNING mlflow.pyfunc: Detected one or more mismatches between the model's dependencies and the current Python environment:
 - psutil (current: 5.9.8, required: psutil==5.9.0)
To fix the mismatches, call `mlflow.pyfunc.get_model_dependencies(model_uri)` to fetch the model's environment and install dependencies using the resulting environment file.
2024/02/02 10:31:45 WARNING mlflow.pyfunc: The version of Python that the model was saved in, `Python 3.9.18`, differs from the version of Python that is currently running, `Python 3.8.10`, and may be incompatible


In [ ]:
loaded_model

In [2]:
import pickle
import os
# Crédentials d'accès à AWS
os.environ['AWS_ACCESS_KEY_ID'] = "AKIA3R62MVALHESATEYJ"
os.environ['AWS_SECRET_ACCESS_KEY'] = "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"
os.environ['ARTIFACT_STORE_URI'] = "s3://isen-mlflow/models/"

import mlflow
logged_model = 'runs:/6f5d7ef26b6c486ba19f859d6720a6cd/model Bank 22'

# Load model as a PyFuncModel.
loaded_model = mlflow.pyfunc.load_model(logged_model)

# Predict on a Pandas DataFrame.
import pandas as pd

MlflowException: Run '6f5d7ef26b6c486ba19f859d6720a6cd' not found

In [1]:
import mlflow
import os

os.environ['AWS_ACCESS_KEY_ID'] = "AKIA3R62MVALHESATEYJ"
os.environ['AWS_SECRET_ACCESS_KEY'] = "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"
os.environ['ARTIFACT_STORE_URI'] = "s3://isen-mlflow/models/"

mlflow.set_tracking_uri("https://isen-brest-mlflow-78c88f4d25fa.herokuapp.com/")

mlflow.set_experiment("Isen - Mlflow PARIS")


mlflow.start_run(run_name="Test - Run")

mlflow.log_metrics({"accuracy": 0.9, "loss": 0.2})


mlflow.log_artifact("./Dockerfile")

/Users/kevinduranty/Desktop/MLOPS/venv_streamlit/lib/python3.8/site-packages/pydantic/_internal/_fields.py:149: UserWarning: Field "model_server_url" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/Users/kevinduranty/Desktop/MLOPS/venv_streamlit/lib/python3.8/site-packages/pydantic/_internal/_config.py:321: UserWarning: Valid config keys have changed in V2:
* 'schema_extra' has been renamed to 'json_schema_extra'
  warnings.warn(message, UserWarning)


In [3]:
mlflow.start_run(run_name="Test - Run")

<ActiveRun: >

In [4]:
mlflow.log_metrics({"accuracy": 0.9, "loss": 0.2})

In [5]:
mlflow.log_artifact("./Dockerfile")

In [ ]:
# Création de l'expérience "Model Classification"
mlflow.set_experiment("Model Test")
mlflow.start_run(run_name="First Run 0")
# Envoi des métriques
mlflow.log_metrics({"accuracy": 0.9, "loss": 0.2})

mlflow.log_artifact("./requirements.txt")

In [4]:
data = {'age': 58,
    'job': 1,
    'marital': 1,
    'education': 2,
    'default': 0,
    'balance': 2143,
    'housing': 1,
    'loan': 0,
    'campaign': 1,
    'pdays': -1,
    'previous': 0,
    'poutcome': 3
}

In [10]:
type(loaded_model.predict(data)[0])

numpy.int64

In [11]:
# Save loaded model in pickle format.
pickle.dump(loaded_model, open("model.pkl", "wb"))

In [2]:
# Load model
import pickle
with open('model.pkl', 'rb') as f: model_ = pickle.load(f)

/Users/kevinduranty/Desktop/my_fastapi/venv_streamlit/lib/python3.8/site-packages/pydantic/_internal/_fields.py:149: UserWarning: Field "model_server_url" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/Users/kevinduranty/Desktop/my_fastapi/venv_streamlit/lib/python3.8/site-packages/pydantic/_internal/_config.py:321: UserWarning: Valid config keys have changed in V2:
* 'schema_extra' has been renamed to 'json_schema_extra'
  warnings.warn(message, UserWarning)


In [5]:

model_.predict(data)

array([0])

In [ ]:
AWS_ACCESS_KEY_ID = 'AKIA3R62MVALIPSJKWGG'
AWS_SECRET_ACCESS_KEY = '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'
ARTIFACT_STORE_URI = 's3://isen-mlflow-brest/models/'